services:
  mysql:
     build: ./Infrastructure/MySQL
     image: soyux/mysql
     environment:
      - MYSQL_ROOT_PASSWORD:"${DB_ROOT_PASSWORD}"
     env_file: .env
     #command: --default-authentication-plugin=mysql_native_password
     ports: 
      - "3306:3306"    
  
  kafka:
    build: ./Infrastructure/Kafka
    image: soyux/kafka
    command: ${KAFKA_INSTALL_DIR}/bin/zookeeper-server-start.sh ${KAFKA_INSTALL_DIR}/config/zookeeper.properties && ${KAFKA_INSTALL_DIR}/bin/kafka-server-start.sh ${KAFKA_INSTALL_DIR}/config/server.properties"] 
    depends_on:
      - mysql
    ports:
      - "9092:9092"
      - "2181:2181"
    #command: tail -f /dev/null
            
  backend-java:
    build:  ./App
    image: soyux/javacode


    