#!/bin/bash
cd ./App/listener
mvn clean install -DskipTests -Dcheckstyle.skip
mvn package
cd ../..
docker compose -f "docker-compose.yaml" down 
docker compose -f "docker-compose.yaml" up -d --build 
