CREATE DATABASE SAMPLE
CREATE TABLE IF NOT EXISTS Countries(id int, name varchar(255))
--REQUIRED FOR DEBEZIUM
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
