services:
  mysql:
     build: ./MySQL
     image: soyux/mysql
     environment:
      - MYSQL_ROOT_PASSWORD:"${DB_ROOT_PASSWORD}"
     env_file: .env
     command: --default-authentication-plugin=mysql_native_password
     ports: 
      - "3306:3306"
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafkaengine:
    build: ./Kafka-Bitnami
    image: soyux/kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    volumes:
      - "kafka_data:/bitnami"
    depends_on:
      - mysql
      - zookeeper      
  backend-java:
    build:  ../Code
    image: soyux/javacode

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


    